web:
  container_name: ideiasnetwork-web
  build: .
  command: bash -c "while [ true ]; do sleep 10; done"
  environment:
    - RAILS_ENV=development
  links:
    - db
  ports:
    - "3000:3000"
  expose:
    - "3000"

db:
  container_name: ideiasnetwork-db
  image: postgres:9.4.5
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
  ports:
    - "5432:5432"
  expose:
    - "5432"
